### ISSUE TITLE
 Declaring variable inside for loop

### ISSUE THREAD

**Issue by janus** [althea-mesh/guac#2]
Declaring variable inside for loop looks a bit strange too me. And it may create a lot of memories in the stack
uint256 hashedOffset;
 uint256 preimageOffset;
for (uint256 i = 0; i < pairs.length; i += 64) {
            hashedOffset = i + 32;
            preimageOffset = i + 64;

            assembly {
                hashed := mload(add(pairs, hashedOffset))
                preimage := mload(add(pairs, preimageOffset))
            }

            submitPreimage(hashed, preimage);
        }
}

**Comment by jtremback** [comment]
I don't see any variables being declared in the loop.

**Comment by jtremback** [comment]
Also, read https://guides.github.com/features/mastering-markdown/ to format code samples better
