### ISSUE TITLE
Missing files error

### ISSUE THREAD

**Issue by janus** [althea-mesh/guac#3]
You have removed the below files from contracts folder, however artifacts would still require them.
By commenting them out this issue is resolved

Error: Could not find artifacts for ./ConvertLib.sol from any sources

//var ConvertLib = artifacts.require("./ConvertLib.sol");
//var MetaCoin = artifacts.require("./MetaCoin.sol");

**Comment by jtremback** [comment]
fixed in a7f38b59ad4674dc28de40a599579658e5bb1c33, thanks
